#!/usr/bin/env node
// Compiles Probe.sol with solc-js and writes Probe.json (abi + bytecode).
//
// Run via `make probe-build` from packages/blockchain, after
// `npm install --no-save solc@0.8.30` in e2e/diff. The output is committed,
// so the differential harness itself never needs solc — this script only
// runs when Probe.sol changes.
//
// evmVersion is pinned to "cancun" to match the pin M08 adds to
// packages/hardhat/hardhat.config.ts (MASTER §3): the fixture must not use
// a newer EVM than the contracts the real deployment compiles under, or the
// harness would prove parity on bytecode the app never actually runs.

import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

let solc;
try {
  solc = require("solc");
} catch {
  console.error(
    "solc is not installed. From packages/blockchain/e2e/diff run:\n" +
      "  npm install --no-save solc@0.8.30\n" +
      "then re-run `make probe-build`.",
  );
  process.exit(2);
}

const SOURCE_NAME = "Probe.sol";
const CONTRACT_NAME = "Probe";

const source = readFileSync(join(here, SOURCE_NAME), "utf8");

const input = {
  language: "Solidity",
  sources: { [SOURCE_NAME]: { content: source } },
  settings: {
    optimizer: { enabled: true, runs: 200 },
    evmVersion: "cancun",
    outputSelection: { "*": { "*": ["abi", "evm.bytecode.object"] } },
  },
};

const output = JSON.parse(solc.compile(JSON.stringify(input)));

const errors = (output.errors ?? []).filter((e) => e.severity === "error");
if (errors.length > 0) {
  for (const e of errors) console.error(e.formattedMessage ?? e.message);
  process.exit(1);
}
for (const w of output.errors ?? []) {
  console.warn(w.formattedMessage ?? w.message);
}

const contract = output.contracts?.[SOURCE_NAME]?.[CONTRACT_NAME];
if (!contract) {
  console.error(`compiler produced no ${CONTRACT_NAME} in ${SOURCE_NAME}`);
  process.exit(1);
}

const artifact = {
  _comment:
    "Generated by contracts/build.mjs from Probe.sol — do not edit by hand. Regenerate with `make probe-build`.",
  contractName: CONTRACT_NAME,
  solcVersion: solc.version(),
  evmVersion: input.settings.evmVersion,
  abi: contract.abi,
  bytecode: "0x" + contract.evm.bytecode.object,
};

const outPath = join(here, `${CONTRACT_NAME}.json`);
writeFileSync(outPath, JSON.stringify(artifact, null, 2) + "\n");
console.log(`wrote ${outPath} (${artifact.bytecode.length / 2 - 1} bytes of init code, solc ${artifact.solcVersion})`);
