// Offline unit tests for ./election-core.mjs.
//
//   node --test lib/election-core.test.mjs
//   (or, from packages/blockchain: `make e2e-core-test`)
//
// No node, no chain, no network, no proving — seconds, not minutes. The full
// election harness is expensive and needs a Go toolchain; the logic most
// likely to be subtly wrong needs neither, so it is tested here.
//
// Two of these suites are worth more than the rest, because they check against
// something OUTSIDE this repo's JavaScript:
//
//   - "against the circuit's own fixture" uses packages/circuits/Prover.toml,
//     whose values were produced independently and verified by `nargo`. If
//     poseidon-lite, the field, or the path-walking bit order ever diverged
//     from what the circuit computes, that suite fails. Testing poseidon
//     against poseidon would not.
//   - "against the compiled circuit's ABI" reads the real circuits.json and
//     asserts our witness object has exactly the parameters the circuit
//     declares, with the declared array length. A renamed or reordered input
//     is caught here rather than as an opaque bb.js failure ten minutes into
//     the gate.

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

import { poseidon2 } from "poseidon-lite";

import {
  CIRCUIT_DEPTH,
  FIELD_PRIME,
  buildCircuitInputs,
  buildMerklePath,
  buildVoteArgs,
  deriveFromSecrets,
  findCircuitIndex,
  generateCommitment,
  leavesFromEvents,
  padSiblings,
  randomFieldElement,
  rebuildTree,
  toBytes32,
} from "./election-core.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const CIRCUITS_JSON = join(here, "..", "..", "..", "nextjs", "public", "circuits.json");

// packages/circuits/Prover.toml, verbatim. Generated by
// packages/nextjs/generate_prover_inputs.mjs and accepted by the circuit, so
// these are known-good values from outside this file's own arithmetic.
const FIXTURE = {
  nullifier: "42",
  secret: "123",
  nullifierHash: "12326503012965816391338144612242952408728683609716147019497703475006801258307",
  root: "14323779011469951618447924429445439226819608782236079685175267553238899867272",
  siblings: ["111", "222", "333"],
  index: 2,
  depth: 3,
};

// ---------------------------------------------------------------------------

test("against the circuit's own fixture", async (t) => {
  await t.test("deriveFromSecrets reproduces the fixture's nullifier hash", () => {
    const { nullifierHash } = deriveFromSecrets(FIXTURE.nullifier, FIXTURE.secret);
    assert.equal(nullifierHash, FIXTURE.nullifierHash);
  });

  await t.test("findCircuitIndex recovers the fixture's index from its root", () => {
    const { commitment } = deriveFromSecrets(FIXTURE.nullifier, FIXTURE.secret);
    const found = findCircuitIndex(commitment, FIXTURE.siblings, FIXTURE.root);
    assert.equal(found, FIXTURE.index);
  });

  await t.test("a wrong root yields no index rather than a plausible one", () => {
    const { commitment } = deriveFromSecrets(FIXTURE.nullifier, FIXTURE.secret);
    const wrongRoot = (BigInt(FIXTURE.root) + 1n).toString();
    assert.equal(findCircuitIndex(commitment, FIXTURE.siblings, wrongRoot), -1);
  });
});

test("against the compiled circuit's ABI", async (t) => {
  const circuit = JSON.parse(readFileSync(CIRCUITS_JSON, "utf8"));
  const params = circuit.abi.parameters;

  await t.test("buildCircuitInputs supplies exactly the declared parameters", () => {
    const inputs = buildCircuitInputs({
      nullifier: FIXTURE.nullifier,
      secret: FIXTURE.secret,
      circuitIndex: FIXTURE.index,
      siblings: FIXTURE.siblings,
      root: FIXTURE.root,
      candidateIndex: 1,
      depth: FIXTURE.depth,
    });
    assert.deepEqual(Object.keys(inputs).sort(), params.map((p) => p.name).sort());
  });

  await t.test("the sibling array length matches the circuit's declaration", () => {
    const siblingsParam = params.find((p) => p.name === "siblings");
    assert.equal(siblingsParam.type.length, CIRCUIT_DEPTH);
  });

  await t.test("every value is a string or an array of strings, as Noir's ABI expects", () => {
    const inputs = buildCircuitInputs({
      nullifier: FIXTURE.nullifier,
      secret: FIXTURE.secret,
      circuitIndex: FIXTURE.index,
      siblings: FIXTURE.siblings,
      root: FIXTURE.root,
      candidateIndex: 1,
      depth: FIXTURE.depth,
    });
    for (const [key, value] of Object.entries(inputs)) {
      if (Array.isArray(value)) {
        assert.equal(value.length, CIRCUIT_DEPTH, `${key} length`);
        for (const item of value) assert.equal(typeof item, "string", `${key} item type`);
      } else {
        assert.equal(typeof value, "string", `${key} type`);
        assert.match(value, /^\d+$/, `${key} should be a decimal string`);
      }
    }
  });
});

// ---------------------------------------------------------------------------

test("commitment generation", async (t) => {
  await t.test("values are inside the BN254 scalar field", () => {
    for (let i = 0; i < 20; i++) {
      assert.ok(randomFieldElement() < FIELD_PRIME);
    }
  });

  await t.test("a commitment is self-consistent", () => {
    const identity = generateCommitment();
    const derived = deriveFromSecrets(identity.nullifier, identity.secret);
    assert.equal(derived.commitment, identity.commitment);
    assert.equal(derived.nullifierHash, identity.nullifierHash);
  });

  await t.test("two commitments differ", () => {
    const a = generateCommitment();
    const b = generateCommitment();
    assert.notEqual(a.commitment, b.commitment);
    assert.notEqual(a.nullifierHash, b.nullifierHash);
  });

  await t.test("every field is a decimal string, never a bigint", () => {
    const identity = generateCommitment();
    for (const value of Object.values(identity)) {
      assert.equal(typeof value, "string");
      assert.match(value, /^\d+$/);
    }
  });
});

// ---------------------------------------------------------------------------

test("leavesFromEvents", async (t) => {
  const event = (index, value) => ({ index, value: BigInt(value) });

  await t.test("orders by the emitted index, not by log order", () => {
    const leaves = leavesFromEvents([event(1, 20), event(0, 10), event(2, 30)], 3);
    assert.deepEqual(leaves, [10n, 20n, 30n]);
  });

  await t.test("keeps only the current election's leaves after a reset", () => {
    // Two elections' worth of logs; resetElection() left the tree at size 2.
    const logs = [event(0, 111), event(1, 222), event(2, 333), event(0, 44), event(1, 55)];
    assert.deepEqual(leavesFromEvents(logs, 2), [44n, 55n]);
  });

  await t.test("accepts bigint indices, as viem decodes uint256", () => {
    assert.deepEqual(leavesFromEvents([event(1n, 20), event(0n, 10)], 2), [10n, 20n]);
  });

  await t.test("refuses to return a short list", () => {
    assert.throws(() => leavesFromEvents([event(0, 10)], 3), /does not match on-chain tree size/);
  });

  await t.test("an empty current election returns no leaves, not every leaf", () => {
    // Regression: `slice(-0)` is `slice(0)`, so a size-0 tree with historic
    // logs would otherwise return the whole history.
    assert.deepEqual(leavesFromEvents([event(0, 111), event(1, 222)], 0), []);
    assert.deepEqual(leavesFromEvents([], 0), []);
  });

  await t.test("rejects a nonsensical tree size", () => {
    assert.throws(() => leavesFromEvents([], -1), /non-negative integer/);
    assert.throws(() => leavesFromEvents([], 1.5), /non-negative integer/);
  });
});

// ---------------------------------------------------------------------------

test("buildMerklePath", async (t) => {
  /** Synthesise the NewLeaf events a division would have emitted for `leaves`. */
  const eventsFor = (leaves) => leaves.map((value, index) => ({ index, value }));

  /**
   * Walk the path the way the CIRCUIT does — little-endian index bits, poseidon2
   * at each level, over the first `depth` siblings — rather than the way LeanIMT
   * does. That is the whole point of the circuit index, so verifying it any
   * other way would verify nothing.
   */
  const circuitRoot = (leaf, siblings, index, depth) => {
    let current = BigInt(leaf);
    for (let level = 0; level < depth; level++) {
      const sibling = BigInt(siblings[level]);
      const isRight = (index >> level) & 1;
      current = isRight ? poseidon2([sibling, current]) : poseidon2([current, sibling]);
    }
    return current;
  };

  for (const size of [1, 2, 3, 5, 8, 9]) {
    await t.test(`a ${size}-leaf tree produces a path the circuit would accept`, () => {
      const identities = Array.from({ length: size }, () => generateCommitment());
      const leaves = identities.map((i) => BigInt(i.commitment));
      const target = identities[Math.floor(size / 2)];

      const path = buildMerklePath({
        leafEvents: eventsFor(leaves),
        treeSize: size,
        commitment: target.commitment,
      });

      assert.equal(path.treeSize, size);
      assert.equal(path.siblings.length, CIRCUIT_DEPTH, "always padded to the circuit's fixed width");
      // depth 0 is legal and reachable: a division with exactly one registered
      // voter has a tree whose root IS the commitment, so the path has no
      // siblings at all. The circuit accepts that (it counts non-zero siblings
      // itself) and Voting.vote()'s only root precondition is that it is
      // non-zero, which a commitment always is.
      assert.ok(path.depth >= 0 && path.depth <= CIRCUIT_DEPTH, `depth ${path.depth} out of range`);
      assert.equal(path.depth === 0, size === 1, "only a single-voter division has an empty path");
      assert.ok(
        path.siblings.slice(path.depth).every((s) => s === "0"),
        "everything past `depth` must be padding",
      );
      assert.equal(BigInt(path.root), rebuildTree(leaves).root, "the root is LeanIMT's own");
      assert.equal(
        circuitRoot(target.commitment, path.siblings, path.circuitIndex, path.depth),
        BigInt(path.root),
        "the circuit's own walk reproduces that root",
      );
    });
  }

  await t.test("an unknown commitment is reported, not silently proved", () => {
    const leaves = [1n, 2n, 3n];
    assert.throws(
      () => buildMerklePath({ leafEvents: eventsFor(leaves), treeSize: 3, commitment: 99n }),
      /commitment not found/,
    );
  });

  await t.test("an empty tree is reported", () => {
    assert.throws(() => buildMerklePath({ leafEvents: [], treeSize: 0, commitment: 1n }), /no voters registered/);
  });

  await t.test("the leaf index is the position in the current election's tree", () => {
    const leaves = [10n, 20n, 30n, 40n];
    const path = buildMerklePath({ leafEvents: eventsFor(leaves), treeSize: 4, commitment: 30n });
    assert.equal(path.leafIndex, 2);
  });
});

// ---------------------------------------------------------------------------

test("padSiblings", async (t) => {
  await t.test("pads to the circuit's fixed length with zeros", () => {
    const padded = padSiblings(["1", "2"]);
    assert.equal(padded.length, CIRCUIT_DEPTH);
    assert.deepEqual(padded.slice(0, 2), ["1", "2"]);
    assert.ok(padded.slice(2).every((s) => s === "0"));
  });

  await t.test("normalises bigints and hex to decimal strings", () => {
    assert.deepEqual(padSiblings([255n, "0xff"]).slice(0, 2), ["255", "255"]);
  });

  await t.test("refuses a path longer than the circuit accepts", () => {
    assert.throws(() => padSiblings(Array(17).fill("1")), /exceeds the circuit's 16/);
  });

  await t.test("leaves an already-full path alone", () => {
    const full = Array.from({ length: CIRCUIT_DEPTH }, (_, i) => String(i + 1));
    assert.deepEqual(padSiblings(full), full);
  });
});

// ---------------------------------------------------------------------------

test("toBytes32", async (t) => {
  await t.test("zero is 32 zero bytes, not '0x0'", () => {
    assert.equal(toBytes32("0"), `0x${"0".repeat(64)}`);
  });

  await t.test("a small value is left-padded", () => {
    assert.equal(toBytes32(1), `0x${"0".repeat(63)}1`);
  });

  await t.test("accepts decimal strings, hex strings and bigints alike", () => {
    assert.equal(toBytes32("255"), toBytes32("0xff"));
    assert.equal(toBytes32(255n), toBytes32("0xff"));
  });

  await t.test("a full-width field element keeps all 64 nibbles", () => {
    const encoded = toBytes32(FIELD_PRIME - 1n);
    assert.equal(encoded.length, 66);
    assert.equal(BigInt(encoded), FIELD_PRIME - 1n);
  });

  await t.test("refuses values that do not fit, rather than truncating", () => {
    assert.throws(() => toBytes32(2n ** 256n), /does not fit in 32 bytes/);
    assert.throws(() => toBytes32(-1n), /negative/);
  });
});

// ---------------------------------------------------------------------------

test("buildVoteArgs", async (t) => {
  const inputs = buildCircuitInputs({
    nullifier: FIXTURE.nullifier,
    secret: FIXTURE.secret,
    circuitIndex: FIXTURE.index,
    siblings: FIXTURE.siblings,
    root: FIXTURE.root,
    candidateIndex: 1,
    depth: FIXTURE.depth,
  });

  await t.test("produces the five arguments Voting.vote() takes", () => {
    const args = buildVoteArgs(inputs, "0xdeadbeef");
    assert.deepEqual(Object.keys(args), ["proof", "nullifierHash", "root", "vote", "depth"]);
    for (const key of ["nullifierHash", "root", "vote", "depth"]) {
      assert.equal(args[key].length, 66, `${key} should be a 32-byte word`);
    }
  });

  await t.test("the encoded words round-trip to the circuit's public inputs", () => {
    const args = buildVoteArgs(inputs, "0x00");
    assert.equal(BigInt(args.nullifierHash).toString(), inputs.nullifier_hash);
    assert.equal(BigInt(args.root).toString(), inputs.root);
    assert.equal(BigInt(args.vote).toString(), inputs.vote);
    assert.equal(BigInt(args.depth).toString(), inputs.depth);
  });

  await t.test("rejects a proof that is not hex", () => {
    assert.throws(() => buildVoteArgs(inputs, "deadbeef"), /0x-prefixed hex/);
    assert.throws(() => buildVoteArgs(inputs, "0xzz"), /0x-prefixed hex/);
    assert.throws(() => buildVoteArgs(inputs, undefined), /0x-prefixed hex/);
  });
});
