name: Run Tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  contracts:
    name: Smart Contract Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: cd packages/hardhat && yarn install
      - run: cd packages/hardhat && npx hardhat test --network hardhat

  web:
    name: Web Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: cd packages/nextjs && yarn install
      - run: cd packages/nextjs && npx next lint
